name: binara_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - clang>=21.1.0
  - clangxx>=21.1.0
  - clang-tools>=21.1.0
  - llvm-openmp>=21.1.0
  - boost>=1.83
  - cmake>=2.28
  - ninja>=1.11
  - pip
  - pip:
      - nanobind
      - pytest
      - bokeh
      - numpy
      - pandas
